on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  IMAGE_NAME: <microservice-name>
  SERVICE_NAME: <microservice-name>
jobs:
  build-and-test:
    name: Build and Unit Test
    ... build process based on language ...
  sonar-scan:
    name: Static Code Analysis (SonarCloud)
    runs-on: ubuntu-latest
    needs: build-and-test
  ...
  xray-scan:
    name: SCA & Dependency Scan (JFrog Xray)
  ...
  build-container:
    name: Build Docker Image
    ... docker build and push to registry...
  artifact-attestation:
    name: Generate artifact attestation for integrity...
  zap-dast:
    name: ZAP scan
    steps:
    - name: ZAP Scan
    uses: zaproxy/action-full-scan@v0.12.0
    with:
    target: 'http://url-to-service' # Replace with actual url
    ...other options
... deploy steps ...
  functional-tests:
    name: Run Functional Tests
    ... functional tests and upload results ...